# Compile time options:
# -DNDEBUG Turn off run time checks in production calculations to gain speed
#NOTE: Using -fast gives wrong output from pbex, disappears at -O2
#level (without ipo) for icpc 10.1.017

# C++ compiler and flags
CXX=icpc
CC=icc
FF=ifort
# Turn of messages that hide real errors
CFLAGS= -DNDEBUG -Wall -g -O2 -wd981 -wd279 -wd383 -wd1572 -wd177
CXXFLAGS=$(CFLAGS) -fno-rtti -fno-exceptions
FFLAGS=-DNDEBUG


include Makefile.common
